### ISSUE TITLE
Add Zigbee2MQTT to the repository

### ISSUE THREAD

**Issue by ishimarumakoto** [mr-manuel/CasaOS-HomeAutomation-AppStore#2]
Hello, I would like to know if it's possible to add Zigbee2MQTT already in the repository.
The instructions can be used from here:
https://www.homeautomationguy.io/blog/youtube-videos/installing-zigbee2mqtt-with-home-assistant

Thanks!

**Comment by ishimarumakoto** [comment]
Hello, I forked and created, if you want to use it feel free :)
https://github.com/ishimarumakoto/CasaOS-HomeAutomation-AppStore/commit/15f5136ffb5c755fd4ead1e63f7323bf57cd8ff8

**Comment by mr-manuel** [comment]
Thanks https://github.com/mr-manuel/CasaOS-HomeAutomation-AppStore/pull/3
